#!/bin/bash

BASE_DIR="frontend/WyaparPayExpo/src/i18n/locales"

# Create Kannada common.json
cat > "$BASE_DIR/kn/common.json" << 'JSON'
{
  "app_name": "ವ್ಯಾಪಾರ ಪೇ",
  "loading": "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
  "error": "ದೋಷ",
  "success": "ಯಶಸ್ಸು",
  "cancel": "ರದ್ದುಮಾಡಿ",
  "continue": "ಮುಂದುವರಿಸಿ",
  "back": "ಹಿಂದೆ",
  "done": "ಮುಗಿದಿದೆ",
  "save": "ಉಳಿಸಿ",
  "edit": "ಸಂಪಾದಿಸಿ",
  "delete": "ಅಳಿಸಿ",
  "confirm": "ದೃಢೀಕರಿಸಿ",
  "yes": "ಹೌದು",
  "no": "ಇಲ್ಲ",
  "ok": "ಸರಿ",
  "retry": "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
  "close": "ಮುಚ್ಚಿ",
  "search": "ಹುಡುಕಿ",
  "filter": "ಫಿಲ್ಟರ್",
  "sort": "ವಿಂಗಡಿಸಿ",
  "refresh": "ರಿಫ್ರೆಶ್ ಮಾಡಿ",
  "view_all": "ಎಲ್ಲಾ ನೋಡಿ",
  "see_details": "ವಿವರಗಳನ್ನು ನೋಡಿ",
  "submit": "ಸಲ್ಲಿಸಿ",
  "send": "ಕಳುಹಿಸಿ",
  "apply": "ಅನ್ವಯಿಸಿ",
  "select": "ಆರಿಸಿ",
  "deselect": "ಆಯ್ಕೆ ರದ್ದುಮಾಡಿ",
  "clear": "ತೆರವುಗೊಳಿಸಿ",
  "reset": "ಮರುಹೊಂದಿಸಿ",
  "update": "ನವೀಕರಿಸಿ",
  "upload": "ಅಪ್ಲೋಡ್ ಮಾಡಿ",
  "download": "ಡೌನ್ಲೋಡ್ ಮಾಡಿ",
  "share": "ಹಂಚಿಕೊಳ್ಳಿ",
  "copy": "ಕಾಪಿ ಮಾಡಿ",
  "paste": "ಅಂಟಿಸಿ",
  "cut": "ಕತ್ತರಿಸಿ",
  "next": "ಮುಂದೆ",
  "previous": "ಹಿಂದಿನದು",
  "skip": "ಬಿಟ್ಟುಬಿಡಿ",
  "finish": "ಮುಗಿಸಿ",
  "logout": "ಲಾಗ್ ಔಟ್",
  "login": "ಲಾಗಿನ್",
  "register": "ನೋಂದಣಿ ಮಾಡಿ",
  "home": "ಹೋಮ್",
  "profile": "ಪ್ರೊಫೈಲ್",
  "settings": "ಸೆಟ್ಟಿಂಗ್ಗಳು",
  "help": "ಸಹಾಯ",
  "about": "ಕುರಿತು",
  "terms": "ನಿಯಮಗಳು ಮತ್ತು ಶರತ್ತುಗಳು",
  "privacy": "ಗೌಪ್ಯತಾ ನೀತಿ",
  "contact": "ಸಂಪರ್ಕಿಸಿ",
  "support": "ಬೆಂಬಲ",
  "faq": "ಆಗಾಗ್ಗೆ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು",
  "feedback": "ಪ್ರತಿಕ್ರಿಯೆ",
  "rate_us": "ನಮಗೆ ರೇಟ್ ಮಾಡಿ",
  "notifications": "ಅಧಿಸೂಚನೆಗಳು",
  "language": "ಭಾಷೆ",
  "theme": "ಥೀಮ್",
  "version": "ಆವೃತ್ತಿ",
  "powered_by": "ನಿಂದ ಚಾಲಿತ"
}
JSON

cat > "$BASE_DIR/kn/dashboard.json" << 'JSON'
{
  "title": "ಡ್ಯಾಶ್ಬೋರ್ಡ್",
  "welcome_message": "ಮರಳಿ ಸ್ವಾಗತ!",
  "wallet_balance": "ವಾಲೆಟ್ ಬ್ಯಾಲೆನ್ಸ್",
  "add_money": "ಹಣ ಸೇರಿಸಿ",
  "send_money": "ಹಣ ಕಳುಹಿಸಿ",
  "quick_actions": "ತ್ವರಿತ ಕ್ರಿಯೆಗಳು",
  "mobile_recharge": "ಮೊಬೈಲ್ ರೀಚಾರ್ಜ್",
  "dth_recharge": "DTH ರೀಚಾರ್ಜ್",
  "electricity_bill": "ವಿದ್ಯುತ್ ಬಿಲ್",
  "water_bill": "ನೀರಿನ ಬಿಲ್",
  "gas_bill": "ಗ್ಯಾಸ್ ಬಿಲ್",
  "broadband_bill": "ಬ್ರಾಡ್ಬ್ಯಾಂಡ್",
  "credit_card": "ಕ್ರೆಡಿಟ್ ಕಾರ್ಡ್",
  "loan_repayment": "ಸಾಲ ಮರುಪಾವತಿ",
  "insurance": "ವಿಮೆ",
  "fastag": "ಫಾಸ್ಟ್ಯಾಗ್",
  "recent_transactions": "ಇತ್ತೀಚಿನ ವ್ಯವಹಾರಗಳು",
  "view_all_transactions": "ಎಲ್ಲಾ ನೋಡಿ",
  "no_transactions": "ಇನ್ನೂ ಯಾವುದೇ ವ್ಯವಹಾರಗಳಿಲ್ಲ",
  "transaction_history": "ವ್ಯವಹಾರ ಇತಿಹಾಸ",
  "recharge_bills": "ರೀಚಾರ್ಜ್ ಮತ್ತು ಬಿಲ್ಗಳು",
  "special_offers": "ವಿಶೇಷ ಆಫರ್ಗಳು",
  "claim": "ಪಡೆದುಕೊಳ್ಳಿ",
  "cashback": "ಕ್ಯಾಶ್ಬ್ಯಾಕ್",
  "offers": "ಆಫರ್ಗಳು",
  "coupons": "ಕೂಪನ್ಗಳು",
  "rewards": "ಬಹುಮಾನಗಳು",
  "referral": "ರೆಫರ್ ಮಾಡಿ ಮತ್ತು ಗಳಿಸಿ",
  "scan_qr": "QR ಸ್ಕ್ಯಾನ್ ಮಾಡಿ",
  "pay_contacts": "ಸಂಪರ್ಕಗಳಿಗೆ ಪಾವತಿಸಿ",
  "bank_transfer": "ಬ್ಯಾಂಕ್ ವರ್ಗಾವಣೆ"
}
JSON

cat > "$BASE_DIR/kn/recharge.json" << 'JSON'
{
  "title": "ಮೊಬೈಲ್ ರೀಚಾರ್ಜ್",
  "subtitle": "ತ್ವರಿತ ಮತ್ತು ಸುಲಭವಾದ ರೀಚಾರ್ಜ್",
  "mobile_number": "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
  "enter_mobile": "10 ಅಂಕಿಯ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
  "select_operator": "ಆಪರೇಟರ್ ಆಯ್ಕೆಮಾಡಿ",
  "select_circle": "ಸರ್ಕಲ್ ಆಯ್ಕೆಮಾಡಿ",
  "auto_detected": "ಸ್ವಯಂ ಪತ್ತೆ",
  "recent_recharges": "ಇತ್ತೀಚಿನ ರೀಚಾರ್ಜ್ಗಳು",
  "continue_to_plans": "ಯೋಜನೆಗಳನ್ನು ನೋಡಿ",
  "browse_plans": "ಯೋಜನೆಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ",
  "select_plan": "ಯೋಜನೆ ಆಯ್ಕೆಮಾಡಿ",
  "popular": "ಜನಪ್ರಿಯ",
  "data": "ಡೇಟಾ",
  "unlimited": "ಅನಿಯಮಿತ",
  "talktime": "ಟಾಕ್ಟೈಮ್",
  "roaming": "ರೋಮಿಂಗ್",
  "sms": "SMS",
  "validity": "ಮಾನ್ಯತೆ",
  "days": "ದಿನಗಳು",
  "day": "ದಿನ",
  "amount": "ಮೊತ್ತ",
  "custom_amount": "ಕಸ್ಟಮ್ ಮೊತ್ತ",
  "enter_amount": "ಮೊತ್ತ ನಮೂದಿಸಿ",
  "plan_details": "ವಿವರಗಳು",
  "benefits": "ಪ್ರಯೋಜನಗಳು",
  "whats_included": "ಏನು ಒಳಗೊಂಡಿದೆ",
  "best_value": "ಉತ್ತಮ ಮೌಲ್ಯ",
  "long_validity": "ದೀರ್ಘ ಮಾನ್ಯತೆ",
  "budget_friendly": "ಬಜೆಟ್ ಸ್ನೇಹಿ",
  "review_pay": "ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಪಾವತಿಸಿ",
  "confirm_recharge": "ನಿಮ್ಮ ರೀಚಾರ್ಜ್ ದೃಢೀಕರಿಸಿ",
  "recharge_amount": "ರೀಚಾರ್ಜ್ ಮೊತ್ತ",
  "instant": "ತತ್ಕ್ಷಣ",
  "recharge_details": "ರೀಚಾರ್ಜ್ ವಿವರಗಳು",
  "operator": "ಆಪರೇಟರ್",
  "circle": "ಸರ್ಕಲ್",
  "payment_method": "ಪಾವತಿ ವಿಧಾನ",
  "wallet_balance": "ವಾಲೆಟ್ ಬ್ಯಾಲೆನ್ಸ್",
  "upi_payment": "UPI ಪಾವತಿ",
  "credit_debit_card": "ಕ್ರೆಡಿಟ್/ಡೆಬಿಟ್ ಕಾರ್ಡ್",
  "pay": "₹{{amount}} ಪಾವತಿಸಿ",
  "processing": "ಪಾವತಿ ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿದೆ...",
  "recharge_successful": "🎉 ರೀಚಾರ್ಜ್ ಯಶಸ್ವಿಯಾಗಿದೆ!",
  "recharge_completed": "ನಿಮ್ಮ ರೀಚಾರ್ಜ್ ಯಶಸ್ವಿಯಾಗಿ ಪೂರ್ಣಗೊಂಡಿದೆ",
  "recharge_failed": "😞 ರೀಚಾರ್ಜ್ ವಿಫಲವಾಗಿದೆ",
  "recharge_error": "ಏನೋ ತಪ್ಪಾಗಿದೆ। ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ।",
  "transaction_id": "ವ್ಯವಹಾರ ID",
  "back_to_dashboard": "ಡ್ಯಾಶ್ಬೋರ್ಡ್ಗೆ ಹಿಂತಿರುಗಿ",
  "view_history": "ಇತಿಹಾಸ ನೋಡಿ",
  "try_again": "ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ",
  "secure_payment": "🔒 end-to-end ಎನ್ಕ್ರಿಪ್ಶನ್ ಜೊತೆ 100% ಸುರಕ್ಷಿತ ಪಾವತಿ",
  "terms_agreement": "ಮುಂದುವರಿಸುವ ಮೂಲಕ, ನೀವು ನಮ್ಮ ನಿಯಮಗಳು ಮತ್ತು ಷರತ್ತುಗಳನ್ನು ಒಪ್ಪುತ್ತೀರಿ"
}
JSON

cat > "$BASE_DIR/kn/profile.json" << 'JSON'
{
  "title": "ಪ್ರೊಫೈಲ್",
  "account_details": "ಖಾತೆ ವಿವರಗಳು",
  "my_account": "ನನ್ನ ಖಾತೆ",
  "personal_info": "ವೈಯಕ್ತಿಕ ಮಾಹಿತಿ",
  "name": "ಹೆಸರು",
  "phone": "ಫೋನ್",
  "email": "ಇಮೇಲ್",
  "email_verified": "ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
  "email_not_verified": "ಪರಿಶೀಲನೆ ಬಾಕಿಯಿದೆ",
  "verify_email": "ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ",
  "preferences": "ಆದ್ಯತೆಗಳು",
  "biometric_login": "ಬಯೋಮೆಟ್ರಿಕ್ ಲಾಗಿನ್",
  "enable_biometric": "ತ್ವರಿತ ಲಾಗಿನ್ಗಾಗಿ ಬಯೋಮೆಟ್ರಿಕ್ ದೃಢೀಕರಣ ಸಕ್ರಿಯಗೊಳಿಸಿ",
  "face_id": "Face ID",
  "touch_id": "Touch ID",
  "fingerprint": "ಫಿಂಗರ್ಪ್ರಿಂಟ್",
  "email_notifications": "ಇಮೇಲ್ ಅಧಿಸೂಚನೆಗಳು",
  "push_notifications": "ಪುಶ್ ಅಧಿಸೂಚನೆಗಳು",
  "sms_notifications": "SMS ಅಧಿಸೂಚನೆಗಳು",
  "security": "ಸುರಕ್ಷತೆ",
  "change_password": "ಪಾಸ್ವರ್ಡ್ ಬದಲಾಯಿಸಿ",
  "current_password": "ಪ್ರಸ್ತುತ ಪಾಸ್ವರ್ಡ್",
  "new_password": "ಹೊಸ ಪಾಸ್ವರ್ಡ್",
  "confirm_password": "ಪಾಸ್ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
  "two_factor_auth": "ಎರಡು-ಅಂಶ ದೃಢೀಕರಣ",
  "about_wyaparpay": "ವ್ಯಾಪಾರ ಪೇ ಕುರಿತು",
  "version": "ಆವೃತ್ತಿ",
  "app_version": "ಆಪ್ ಆವೃತ್ತಿ",
  "terms_conditions": "ನಿಯಮಗಳು ಮತ್ತು ಶರತ್ತುಗಳು",
  "privacy_policy": "ಗೌಪ್ಯತಾ ನೀತಿ",
  "help_support": "ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ",
  "contact_support": "ಬೆಂಬಲ ಸಂಪರ್ಕಿಸಿ",
  "faq": "ಆಗಾಗ್ಗೆ ಕೇಳಲಾಗುವ ಪ್ರಶ್ನೆಗಳು",
  "rate_app": "ಈ ಆಪ್ ರೇಟ್ ಮಾಡಿ",
  "share_app": "ಸ್ನೇಹಿತರೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳಿ",
  "logout": "ಲಾಗ್ ಔಟ್",
  "logout_confirmation": "ನೀವು ನಿಜವಾಗಿಯೂ ಲಾಗ್ ಔಟ್ ಮಾಡಲು ಬಯಸುವಿರಾ?",
  "delete_account": "ಖಾತೆ ಅಳಿಸಿ",
  "delete_account_warning": "ಈ ಕ್ರಿಯೆಯನ್ನು ರದ್ದುಗೊಳಿಸಲಾಗುವುದಿಲ್ಲ",
  "language": "ಭಾಷೆ",
  "select_language": "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
  "english": "English",
  "hindi": "हिंदी",
  "kannada": "ಕನ್ನಡ"
}
JSON

cat > "$BASE_DIR/kn/auth.json" << 'JSON'
{
  "welcome": "ವ್ಯಾಪಾರ ಪೇಗೆ ಸ್ವಾಗತ",
  "tagline": "ನಿಮ್ಮ ವಿಶ್ವಾಸಾರ್ಹ ಪಾವತಿ ಪಾಲುದಾರ",
  "get_started": "ಪ್ರಾರಂಭಿಸಿ",
  "login": "ಲಾಗಿನ್",
  "login_with_password": "ಪಾಸ್ವರ್ಡ್ನೊಂದಿಗೆ ಲಾಗಿನ್ ಮಾಡಿ",
  "login_with_otp": "OTP ನೊಂದಿಗೆ ಲಾಗಿನ್ ಮಾಡಿ",
  "login_with_biometric": "{{type}} ನೊಂದಿಗೆ ಲಾಗಿನ್ ಮಾಡಿ",
  "register": "ನೋಂದಣಿ ಮಾಡಿ",
  "create_account": "ಖಾತೆ ರಚಿಸಿ",
  "already_have_account": "ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ?",
  "dont_have_account": "ಖಾತೆ ಇಲ್ಲವೇ?",
  "phone_or_email": "ಫೋನ್ ಅಥವಾ ಇಮೇಲ್",
  "phone_number": "ಫೋನ್ ಸಂಖ್ಯೆ",
  "email_address": "ಇಮೇಲ್ ವಿಳಾಸ",
  "password": "ಪಾಸ್ವರ್ಡ್",
  "confirm_password": "ಪಾಸ್ವರ್ಡ್ ದೃಢೀಕರಿಸಿ",
  "full_name": "ಪೂರ್ಣ ಹೆಸರು",
  "enter_phone": "ನಿಮ್ಮ ಫೋನ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
  "enter_email": "ನಿಮ್ಮ ಇಮೇಲ್ ವಿಳಾಸ ನಮೂದಿಸಿ",
  "enter_password": "ನಿಮ್ಮ ಪಾಸ್ವರ್ಡ್ ನಮೂದಿಸಿ",
  "enter_name": "ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು ನಮೂದಿಸಿ",
  "phone_helper": "10 ಅಂಕಿಗಳು, 6-9 ರಿಂದ ಪ್ರಾರಂಭವಾಗುತ್ತದೆ",
  "password_helper": "ಕನಿಷ್ಠ 8 ಅಕ್ಷರಗಳು, 1 ದೊಡ್ಡಕ್ಷರ, 1 ಸಣ್ಣಕ್ಷರ, 1 ಸಂಖ್ಯೆ",
  "forgot_password": "ಪಾಸ್ವರ್ಡ್ ಮರೆತಿರಾ?",
  "reset_password": "ಪಾಸ್ವರ್ಡ್ ಮರುಹೊಂದಿಸಿ",
  "send_otp": "OTP ಕಳುಹಿಸಿ",
  "resend_otp": "OTP ಮತ್ತೆ ಕಳುಹಿಸಿ",
  "verify_otp": "OTP ಪರಿಶೀಲಿಸಿ",
  "enter_otp": "OTP ನಮೂದಿಸಿ",
  "otp_sent": "{{identifier}} ಗೆ OTP ಕಳುಹಿಸಲಾಗಿದೆ",
  "otp_helper": "6 ಅಂಕಿಯ ಕೋಡ್ ನಮೂದಿಸಿ",
  "verify_email": "ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ",
  "email_verification": "ಇಮೇಲ್ ಪರಿಶೀಲನೆ",
  "verification_code": "ಪರಿಶೀಲನೆ ಕೋಡ್",
  "enter_verification_code": "ಪರಿಶೀಲನೆ ಕೋಡ್ ನಮೂದಿಸಿ",
  "code_sent": "ನಿಮ್ಮ ಇಮೇಲ್ಗೆ ಪರಿಶೀಲನೆ ಕೋಡ್ ಕಳುಹಿಸಲಾಗಿದೆ",
  "resend_code": "ಕೋಡ್ ಮತ್ತೆ ಕಳುಹಿಸಿ",
  "login_success": "ಲಾಗಿನ್ ಯಶಸ್ವಿಯಾಗಿದೆ!",
  "registration_success": "ನೋಂದಣಿ ಯಶಸ್ವಿಯಾಗಿದೆ!",
  "verify_email_prompt": "ಮುಂದುವರಿಸಲು ದಯವಿಟ್ಟು ನಿಮ್ಮ ಇಮೇಲ್ ಪರಿಶೀಲಿಸಿ",
  "terms_agreement": "ನೋಂದಣಿ ಮಾಡುವ ಮೂಲಕ, ನೀವು ನಮ್ಮನ್ನು ಒಪ್ಪುತ್ತೀರಿ",
  "terms": "ನಿಯಮಗಳು",
  "and": "ಮತ್ತು",
  "privacy": "ಗೌಪ್ಯತಾ ನೀತಿ",
  "or": "ಅಥವಾ"
}
JSON

cat > "$BASE_DIR/kn/errors.json" << 'JSON'
{
  "network_error": "ನೆಟ್ವರ್ಕ್ ಸಂಪರ್ಕ ವಿಫಲವಾಗಿದೆ। ದಯವಿಟ್ಟು ನಿಮ್ಮ ಇಂಟರ್ನೆಟ್ ಪರಿಶೀಲಿಸಿ।",
  "server_error": "ಸರ್ವರ್ ದೋಷ। ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ।",
  "timeout_error": "ವಿನಂತಿ ಸಮಯ ಮುಗಿದಿದೆ। ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ।",
  "unauthorized": "ಅನಧಿಕೃತ। ದಯವಿಟ್ಟು ಮತ್ತೆ ಲಾಗಿನ್ ಮಾಡಿ।",
  "forbidden": "ಪ್ರವೇಶ ನಿಷೇಧ।",
  "not_found": "ಸಂಪನ್ಮೂಲ ಸಿಗಲಿಲ್ಲ।",
  "validation_error": "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಇನ್ಪುಟ್ ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ।",
  "invalid_credentials": "ಅಮಾನ್ಯ ಬಳಕೆದಾರಹೆಸರು ಅಥವಾ ಪಾಸ್ವರ್ಡ್।",
  "invalid_phone": "ಅಮಾನ್ಯ ಫೋನ್ ಸಂಖ್ಯೆ ಫಾರ್ಮ್ಯಾಟ್।",
  "invalid_email": "ಅಮಾನ್ಯ ಇಮೇಲ್ ವಿಳಾಸ।",
  "invalid_password": "ಪಾಸ್ವರ್ಡ್ ಅವಶ್ಯಕತೆಗಳನ್ನು ಪೂರೈಸುವುದಿಲ್ಲ।",
  "passwords_dont_match": "ಪಾಸ್ವರ್ಡ್ಗಳು ಹೊಂದಿಕೆಯಾಗುವುದಿಲ್ಲ।",
  "phone_exists": "ಫೋನ್ ಸಂಖ್ಯೆ ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಲಾಗಿದೆ।",
  "email_exists": "ಇಮೇಲ್ ವಿಳಾಸ ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಲಾಗಿದೆ।",
  "user_not_found": "ಬಳಕೆದಾರ ಸಿಗಲಿಲ್ಲ।",
  "account_locked": "ಖಾತೆ ಲಾಕ್ ಆಗಿದೆ। ದಯವಿಟ್ಟು ಬೆಂಬಲ ಸಂಪರ್ಕಿಸಿ।",
  "session_expired": "ಸೆಷನ್ ಮುಗಿದಿದೆ। ದಯವಿಟ್ಟು ಮತ್ತೆ ಲಾಗಿನ್ ಮಾಡಿ।",
  "invalid_otp": "ಅಮಾನ್ಯ ಅಥವಾ ಮುಗಿದ OTP।",
  "otp_expired": "OTP ಮುಗಿದಿದೆ। ದಯವಿಟ್ಟು ಹೊಸದನ್ನು ವಿನಂತಿಸಿ।",
  "too_many_attempts": "ಹಲವಾರು ಪ್ರಯತ್ನಗಳು। ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ।",
  "insufficient_balance": "ಅಸಮರ್ಪಕ ವಾಲೆಟ್ ಬ್ಯಾಲೆನ್ಸ್।",
  "transaction_failed": "ವ್ಯವಹಾರ ವಿಫಲವಾಗಿದೆ। ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ।",
  "recharge_failed": "ರೀಚಾರ್ಜ್ ವಿಫಲವಾಗಿದೆ। ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ।",
  "payment_failed": "ಪಾವತಿ ವಿಫಲವಾಗಿದೆ। ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ।",
  "operator_not_found": "ಆಪರೇಟರ್ ಸಿಗಲಿಲ್ಲ।",
  "plan_not_found": "ಯೋಜನೆ ಸಿಗಲಿಲ್ಲ।",
  "something_went_wrong": "ಏನೋ ತಪ್ಪಾಗಿದೆ। ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ।",
  "feature_unavailable": "ಈ ವೈಶಿಷ್ಟ್ಯ ಪ್ರಸ್ತುತ ಲಭ್ಯವಿಲ್ಲ।",
  "maintenance_mode": "ಆಪ್ ನಿರ್ವಹಣೆಯಲ್ಲಿದೆ। ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ।",
  "update_required": "ಮುಂದುವರಿಸಲು ದಯವಿಟ್ಟು ಆಪ್ ನವೀಕರಿಸಿ।",
  "permission_denied": "ಅನುಮತಿ ನಿರಾಕರಿಸಲಾಗಿದೆ।",
  "camera_permission": "ಕ್ಯಾಮೆರಾ ಅನುಮತಿ ಅಗತ್ಯವಿದೆ।",
  "location_permission": "ಸ್ಥಳ ಅನುಮತಿ ಅಗತ್ಯವಿದೆ।",
  "biometric_not_available": "ಈ ಸಾಧನದಲ್ಲಿ ಬಯೋಮೆಟ್ರಿಕ್ ದೃಢೀಕರಣ ಲಭ್ಯವಿಲ್ಲ।",
  "biometric_not_enrolled": "ಯಾವುದೇ ಬಯೋಮೆಟ್ರಿಕ್ ಡೇಟಾ ನೋಂದಾಯಿಸಲಾಗಿಲ್ಲ। ದಯವಿಟ್ಟು ಸಾಧನ ಸೆಟ್ಟಿಂಗ್ಗಳಲ್ಲಿ ಹೊಂದಿಸಿ।",
  "biometric_failed": "ಬಯೋಮೆಟ್ರಿಕ್ ದೃಢೀಕರಣ ವಿಫಲವಾಗಿದೆ।",
  "try_again": "ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ।"
}
JSON

echo "Kannada translations created successfully!"
